import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased w-screen min-h-screen`}>
        <div className="min-h-screen h-full max-w-xl mx-auto border border-red-500 overflow-hidden">
          <div className="w-full h-ful border-r border-neutral-200">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
